# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180528_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title'], 'verbose_name': 'Иллюстрация', 'verbose_name_plural': 'Иллюстрации'},
        ),
        migrations.AddField(
            model_name='photo',
            name='captions',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
