# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180529_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(help_text='Enter a name album', max_length=200),
        ),
    ]
